version: '3'

services:
  memc_load_lint_test:
    build:
        context: .
        dockerfile: Dockerfile.ci
    ports:
      - "8000:80"
    depends_on:
        - memcached_idfa
        - memcached_gaid
        - memcached_adid
        - memcached_dvid
    networks:
        - custom
  memcached_idfa:
      image: memcached:latest
      container_name: memcached_idfa
      ports:
          - "11212:11211"
      networks:
          - custom
  memcached_gaid:
      image: memcached:latest
      container_name: memcached_gaid
      ports:
          - "11213:11211"
      networks:
          - custom
  memcached_adid:
      image: memcached:latest
      container_name: memcached_adid
      ports:
          - "11214:11211"
      networks:
          - custom
  memcached_dvid:
      image: memcached:latest
      container_name: memcached_dvid
      ports:
          - "11215:11211"
      networks:
          - custom
networks:
    custom:
        driver: bridge
