version: '3'

services:
  memc_load_lint_test:
    build:
        context: .
        dockerfile: Dockerfile.ci
    ports:
      - "8000:80"
  memcached_idfa:
      image: memcached:latest
      container_name: memcached_idfa
      ports:
          - "11212:11211"
  memcached_gaid:
      image: memcached:latest
      container_name: memcached_gaid
      ports:
          - "11213:11211"
  memcached_adid:
      image: memcached:latest
      container_name: memcached_adid
      ports:
          - "11214:11211"
  memcached_dvid:
      image: memcached:latest
      container_name: memcached_dvid
      ports:
          - "11215:11211"
